version: '3.8'

services:
  api:
    build: .
    ports:
      - "1000:1000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - bakery-net

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bakery-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api-docs.yml:/usr/share/nginx/html/api-docs.yml
    environment:
      - SPEC_URL=api-docs.yml
    networks:
      - bakery-net

volumes:
  mysql_data:

networks:
  bakery-net:
    driver: bridge